namespace ADatabase
{
    public enum ColumnTypeName
    {
        BinaryDouble,
        BinaryFloat,
        Blob,
        Bool,
        Char,
        Date,
        DateTime,
        Dec,
        Float,
        Guid,
        Int,
        Int16,
        Int64,
        Int8,
        LongText,
        Money,
        NChar,
        NLongText,
        NVarchar,
        OldRaw,
        Raw,
        SmallDateTime,
        SmallMoney,
        Text,
        Timestamp,
        Varchar,
        Xml
    }
}